// Generates data/planned.js (window.PLANNED) from data/planned-source.xlsx
// Standalone dataset for the "Planlanan Kategoriler & Filtreler" tab.
// Source sheet: "Arama Hacmi - Cinsiyet Çapraz 2" (7 meta cols + 29 monthly cols Jan2024..May2026)
const XLSX = require('xlsx');
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', 'data', 'planned-source.xlsx');
const OUT = path.join(__dirname, '..', 'data', 'planned.js');
const SHEET = 'Arama Hacmi - Cinsiyet Çapraz 2';

// 69 kategori -> 9 üst grup (Kat 1). facet_planning gruplarına dayanır.
const KAT1_GROUPS = [
  'Üst Giyim', 'Alt Giyim', 'Dış Giyim', 'Elbise & Abiye',
  'İç Giyim & Plaj', 'Aksesuar', 'Takı & Saat', 'Ayakkabı', 'Diğer'
];
const KAT1_COLORS = {
  'Üst Giyim':'#4E79A7', 'Alt Giyim':'#F28E2B', 'Dış Giyim':'#E15759',
  'Elbise & Abiye':'#76B7B2', 'İç Giyim & Plaj':'#59A14F', 'Aksesuar':'#EDC948',
  'Takı & Saat':'#B07AA1', 'Ayakkabı':'#FF9DA7', 'Diğer':'#9C755F'
};
const CAT_TO_KAT1 = {};
const G = (grp, cats) => cats.forEach(c => CAT_TO_KAT1[c] = grp);
G('Üst Giyim', ['Atlet','Bluz','Body','Büstiyer','Gömlek','Hırka','Kazak','Korse','Sweatshirt','Süveter','T-Shirt','Tunik']);
G('Alt Giyim', ['Bermuda','Eşofman','Eşofman Altı','Eşofman Üstü','Etek','Jeans','Kapri','Pantolon','Şort','Tayt']);
G('Dış Giyim', ['Ceket','Kaban','Mont','Pardösü','Polar','Rüzgarlık','Trençkot','Yağmurluk','Yelek']);
G('Elbise & Abiye', ['Abiye','Elbise','Kaftan','Kimono','Salopet','Tulum']);
G('İç Giyim & Plaj', ['Bikini','Boxer','Gecelik','Jüpon','Külot','Mayo','Pareo','Pijama','Sabahlık','Sütyen','İçlik']);
G('Aksesuar', ['Atkı','Cüzdan','Eldiven','Eşarp','Gözlük','Kemer','Kravat','Valiz','Çanta','Çorap','Şal','Şapka','Şemsiye']);
G('Takı & Saat', ['Bileklik','Kolye','Küpe','Saat','Yüzük']);
G('Ayakkabı', ['Ayakkabı']);
G('Diğer', ['Takım','Tesettür']);

const wb = XLSX.readFile(SRC);
const ws = wb.Sheets[SHEET];
if (!ws) throw new Error('Sheet bulunamadı: ' + SHEET);
const rows = XLSX.utils.sheet_to_json(ws, { header: 1, raw: true, defval: null });
const header = rows[0];

// Meta kolon indexleri
const col = (name) => header.findIndex(h => String(h).trim() === name);
const iKat = col('Kök Terim (Kategori)');
const iCins = col('Cinsiyet');
const iMarka = col('Marka');
const iFt = col('Filtre Tipi');
const iFa = col('Filtre Adı (Değer)');
const iKw = col('Arama İfadesi');
// Aylık kolonlar: "Arama İfadesi"den sonraki 29 kolon (Jan2024..May2026)
const mStart = iKw + 1;
const N_MONTHS = 29; // 24 (2024-25) + 5 (2026 Oca-May)

const num = v => (v == null || v === '' || isNaN(v)) ? 0 : Number(v);

const out = [];
const uncatewd = new Set();
for (let r = 1; r < rows.length; r++) {
  const row = rows[r];
  if (!row || row[iKw] == null) continue;
  const kategori = String(row[iKat] || '').trim();
  const monthly = [];
  for (let m = 0; m < N_MONTHS; m++) monthly.push(num(row[mStart + m]));

  const m2024 = monthly.slice(0, 12);
  const m2025 = monthly.slice(12, 24);
  const m2026 = monthly.slice(24, 29); // Oca-May 2026

  const avg2026 = Math.round(m2026.reduce((a, b) => a + b, 0) / 5);
  if (avg2026 <= 0) continue; // sadece hacmi olan kelimeler

  // 12-aylık mevsimsellik: her takvim ayını mevcut yıllar boyunca ortalama
  const m12 = [];
  for (let mo = 0; mo < 12; mo++) {
    const vals = [m2024[mo], m2025[mo]];
    if (mo < 5) vals.push(m2026[mo]); // 2026 sadece Oca-May
    m12.push(Math.round(vals.reduce((a, b) => a + b, 0) / vals.length));
  }
  const s24 = m2024.reduce((a, b) => a + b, 0);
  const s25 = m2025.reduce((a, b) => a + b, 0);
  const yoy = s24 > 0 ? (s25 - s24) / s24 : null;

  const kat1 = CAT_TO_KAT1[kategori] || 'Diğer';
  if (!CAT_TO_KAT1[kategori]) uncatewd.add(kategori);

  out.push({
    c: kategori,
    g: kat1,
    x: (row[iCins] || '').toString().trim(),  // cinsiyet ('' = jenerik)
    b: (row[iMarka] || '').toString().trim(),  // marka ('' = markasız)
    ft: (row[iFt] || '').toString().trim(),    // filtre tipi
    fa: (row[iFa] || '').toString().trim(),     // filtre adı (değer)
    kw: String(row[iKw]).trim(),
    v: avg2026,
    y: yoy == null ? null : Math.round(yoy * 1000) / 1000,
    m: m12
  });
}

if (uncatewd.size) console.warn('UYARI — grupsuz kategori:', [...uncatewd]);

const TR_MONTHS = ['Oca','Şub','Mar','Nis','May','Haz','Tem','Ağu','Eyl','Eki','Kas','Ara'];
const PLANNED = {
  kat1Groups: KAT1_GROUPS,
  kat1Colors: KAT1_COLORS,
  catToKat1: CAT_TO_KAT1,
  months: TR_MONTHS,
  totalKeywords: out.length,
  keywords: out
};

const body =
  '// Generated by scripts/build-planned.js — do not edit by hand.\n' +
  '// Source: data/planned-source.xlsx | Standalone "Planlanan Kategoriler & Filtreler" tab\n' +
  'window.PLANNED = ' + JSON.stringify(PLANNED) + ';\n';
fs.writeFileSync(OUT, body, 'utf8');

const mb = (fs.statSync(OUT).size / 1048576).toFixed(2);
console.log(`planned.js yazıldı: ${out.length} keyword, ${mb} MB`);
// özet
const byKat1 = {};
for (const k of out) byKat1[k.g] = (byKat1[k.g] || 0) + 1;
console.log('Kat1 dağılımı:', byKat1);
